/**
 * End-to-end encryption for messages and files.
 *
 * Uses AES-GCM (authenticated encryption). The room key is generated by the
 * room creator and shared with approved joiners over the WebRTC data channel
 * (via a `key` action) — never over IPFS or any server. All text and file
 * content is encrypted before sending and decrypted on receipt.
 *
 * Wire format: base64-encoded `iv || ciphertext` (12-byte IV + encrypted payload).
 */

const enc = new TextEncoder()
const dec = new TextDecoder()

/** Alias for the WebCrypto CryptoKey type. */
export type CryptoKeyLike = CryptoKey

/** Generate a fresh 256-bit AES-GCM key. */
export async function generateRoomKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, [
    'encrypt',
    'decrypt',
  ])
}

/** Export a CryptoKey to a base64 string (for storage / transport). */
export async function exportKey(key: CryptoKey): Promise<string> {
  const raw = await crypto.subtle.exportKey('raw', key)
  return bytesToBase64(new Uint8Array(raw))
}

/** Import a base64 key string back into a CryptoKey. */
export async function importKey(b64: string): Promise<CryptoKey> {
  const raw = base64ToBytes(b64)
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM', length: 256 }, true, [
    'encrypt',
    'decrypt',
  ])
}

/** Encrypt a UTF-8 string. Returns base64(iv + ciphertext). */
export async function encryptText(key: CryptoKey, plaintext: string): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(12))
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, enc.encode(plaintext))
  const combined = new Uint8Array(iv.length + ct.byteLength)
  combined.set(iv, 0)
  combined.set(new Uint8Array(ct), iv.length)
  return bytesToBase64(combined)
}

/** Decrypt a base64(iv + ciphertext) back to a UTF-8 string. */
export async function decryptText(key: CryptoKey, payload: string): Promise<string> {
  const combined = base64ToBytes(payload)
  const iv = combined.slice(0, 12)
  const ct = combined.slice(12)
  const pt = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, ct)
  return dec.decode(pt)
}

/** Encrypt raw bytes (for file content). Returns base64(iv + ciphertext). */
export async function encryptBytes(key: CryptoKey, data: Uint8Array): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(12))
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, data)
  const combined = new Uint8Array(iv.length + ct.byteLength)
  combined.set(iv, 0)
  combined.set(new Uint8Array(ct), iv.length)
  return bytesToBase64(combined)
}

/** Decrypt base64(iv + ciphertext) back to raw bytes. */
export async function decryptBytes(key: CryptoKey, payload: string): Promise<Uint8Array> {
  const combined = base64ToBytes(payload)
  const iv = combined.slice(0, 12)
  const ct = combined.slice(12)
  const pt = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, ct)
  return new Uint8Array(pt)
}

// --- base64 helpers (handle Uint8Array without chunking issues) ---

function bytesToBase64(bytes: Uint8Array): string {
  let binary = ''
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i])
  return btoa(binary)
}

function base64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64)
  const out = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i)
  return out
}
